### ISSUE TITLE
Livereload not working

### ISSUE THREAD

**Issue by diptajitbasak** [letsgo-framework/letsgo-cli#4]
`letsgo-cli r -l` not running. Need to install `https://github.com/gravityblast/fresh` with `https://github.com/gravityblast/fresh` separately to make it working

**Comment by asabya** [comment]
Under the hood `letsgo-cli` uses `fresh` to livereload. So Install that package seperately `go get github.com/pilu/fresh`. Everything should work fine. After installing fresh you can also run `fresh` to livereload.

**Comment by asabya** [comment]
Updated in docs : https://letsgo-framework.github.io/cli/CLI.html#install-letsgo-cli
